plugin:
 build: .
 volumes:
  - .:/home/app/current
 command: npm run intTest
 environment:
  DEBUG: true
  NODE_ENV: development
 links:
  - postgres:postgres
postgres:
 image: postgres
 environment:
   - LANG=en_US.UTF-8
   - POSTGRES_PASSWORD=password
   - POSTGRES_USER=methodfitness
 ports:
   - 5432:5432